# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

FACEBOOK_APP_ID: 647308731995408
FACEBOOK_APP_SECRET: 94172ee829de2383d9067b71ec66e514

AWS_ACCESS_KEY_ID:  "AKIAJF5RFYLJ2EBE3HGQ"
AWS_SECRET_ACCESS_KEY:  "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"


AWS_BUCKET_DEV:     "lunchlord"

AWS_BUCKET_PRO:     "lunchlord_production"